### PR TITLE
docs: correct spelling of SUBNETWORK

### PR DESCRIPTION
**Pull request by adityaongit**
Changed the wrong spelling of Subetwork to Subnetwork

### CODE REVIEW

**Review by shakeebshams — APPROVED** [review]
LGTM

**Review by adityaongit — COMMENTED** [review]
Please Merge this change.

**Review by apeabody — CHANGES_REQUESTED** [review]
Thanks for the contribution @adityaongit!

Can you please update the source to match: https://github.com/adityaongit/terraform-google-composer/blob/adityaongit-patch-1/variables.tf#L43

**Pull request closed without merging**
